chore: test

diff --git a/.github/workflows/verify-maintenance-branch.yml b/.github/workflows/verify-maintenance-branch.yml
--- a/.github/workflows/verify-maintenance-branch.yml
+++ b/.github/workflows/verify-maintenance-branch.yml
@@ -15,7 +15,8 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Verify that maintenance branch exists for version upgrades
+      - name: Set common variables
+        id: vars
         run: |
           PROPERTIES_FILE="gradle.properties"
           MC_VERSION_REGEX='minecraft_version\s*=\s*(.+)'
@@ -34,8 +35,14 @@ jobs:
             exit 1
           fi
 
-          echo "PR Minecraft Version: $NEW_MC_VERSION"
-          echo "Base (main) Minecraft Version: $OLD_MC_VERSION"
+          echo "new_mc_version=$NEW_MC_VERSION" >> $GITHUB_OUTPUT
+          echo "old_mc_version=$OLD_MC_VERSION" >> $GITHUB_OUTPUT
+
+      - name: Verify that maintenance branch exists for version upgrades (for merges to main)
+        if: github.base_ref == 'main'
+        run: |
+          NEW_MC_VERSION="${{ steps.vars.outputs.new_mc_version }}"
+          OLD_MC_VERSION="${{ steps.vars.outputs.old_mc_version }}"
 
           if [[ "$NEW_MC_VERSION" != "$OLD_MC_VERSION" ]]; then
             echo "Minecraft version change detected: $OLD_MC_VERSION -> $NEW_MC_VERSION"
@@ -58,5 +65,20 @@ jobs:
             fi
           else
             echo "No Minecraft version change detected. Check not required."
+            exit 0
+          fi
+      
+      - name: Verify that Minecraft version was not changed (for merges to maintenance branches)
+        if: startsWith(github.base_ref, 'mc/')
+        run: |
+          NEW_MC_VERSION="${{ steps.vars.outputs.new_mc_version }}"
+          OLD_MC_VERSION="${{ steps.vars.outputs.old_mc_version }}"
+
+          if [[ "$NEW_MC_VERSION" != "$OLD_MC_VERSION" ]]; then
+            echo "❌ Failure: Minecraft version change detected in maintenance branch."
+            echo "You cannot change the Minecraft version in a maintenance branch."
+            exit 1
+          else
+            echo "✅ Success: No Minecraft version change detected in maintenance branch."
             exit 0
           fi
